import rootReducer from '../../reducers/rootReducer';


describe('rootReducer', () => {
  describe('INITIAL_STATE', () => {
    it('is correct', () => {
      const action = { type: 'DUMMY_ACTION' };
      const initialState = {
        currentPerson: {},
        filter: [],
        modalOpen: false,
        request: {
          isFetching: false, query: '', receivedAt: 0, requestedAt: 0, result: [], searchTerm: '',
        },
        timeout: -1,
      };

      expect(rootReducer(undefined, action)).toEqual(initialState);
    });
  });

  // The following tests are autogenerated by redux devtools
  // This test would be much better as a snapshot test,
  // but we wanted do demonstrate these kinds of tests.
  describe('autogenerated tests by redux dev tools', () => {
    describe('clicking on C-3PO card', () => {
      it('correctly updates state', () => {
        let state;
        state = rootReducer({
          currentPerson: {},
          modalOpen: false,
          request: {
            isFetching: false,
            query: 'http://it2810-06.idi.ntnu.no/api/api/people?search=luke',
            requestedAt: 1542237712722,
            result: [{
              id: 1,
              name: 'Luke Skywalker',
              height: '172',
              mass: '77',
              hair_color: 'blond',
              skin_color: 'fair',
              eye_color: 'blue',
              birth_year: '19BBY',
              gender: 'male',
              homeworld: 1,
              SpeciesId: null,
              Planet: {
                id: 1, climate: 'arid', surface_water: '1', name: 'Tatooine', diameter: '10465', rotation_period: '23', terrain: 'desert', gravity: '1 standard', orbital_period: '304', population: '200000',
              },
            }],
            searchTerm: 'luke',
          },
          timeout: 34,
          filter: [],
        }, {
          type: 'SET_CURRENT_PERSON',
          data: {
            id: 1,
            name: 'Luke Skywalker',
            height: '172',
            mass: '77',
            hair_color: 'blond',
            skin_color: 'fair',
            eye_color: 'blue',
            birth_year: '19BBY',
            gender: 'male',
            homeworld: 1,
            SpeciesId: null,
            Planet: {
              id: 1, climate: 'arid', surface_water: '1', name: 'Tatooine', diameter: '10465', rotation_period: '23', terrain: 'desert', gravity: '1 standard', orbital_period: '304', population: '200000',
            },
          },
        });
        expect(state).toEqual({
          currentPerson: {
            id: 1,
            name: 'Luke Skywalker',
            height: '172',
            mass: '77',
            hair_color: 'blond',
            skin_color: 'fair',
            eye_color: 'blue',
            birth_year: '19BBY',
            gender: 'male',
            homeworld: 1,
            SpeciesId: null,
            Planet: {
              id: 1, climate: 'arid', surface_water: '1', name: 'Tatooine', diameter: '10465', rotation_period: '23', terrain: 'desert', gravity: '1 standard', orbital_period: '304', population: '200000',
            },
          },
          modalOpen: false,
          request: {
            isFetching: false,
            query: 'http://it2810-06.idi.ntnu.no/api/api/people?search=luke',
            requestedAt: 1542237712722,
            result: [{
              id: 1,
              name: 'Luke Skywalker',
              height: '172',
              mass: '77',
              hair_color: 'blond',
              skin_color: 'fair',
              eye_color: 'blue',
              birth_year: '19BBY',
              gender: 'male',
              homeworld: 1,
              SpeciesId: null,
              Planet: {
                id: 1, climate: 'arid', surface_water: '1', name: 'Tatooine', diameter: '10465', rotation_period: '23', terrain: 'desert', gravity: '1 standard', orbital_period: '304', population: '200000',
              },
            }],
            searchTerm: 'luke',
          },
          timeout: 34,
          filter: [],
        });
        state = rootReducer({
          currentPerson: {
            id: 1,
            name: 'Luke Skywalker',
            height: '172',
            mass: '77',
            hair_color: 'blond',
            skin_color: 'fair',
            eye_color: 'blue',
            birth_year: '19BBY',
            gender: 'male',
            homeworld: 1,
            SpeciesId: null,
            Planet: {
              id: 1, climate: 'arid', surface_water: '1', name: 'Tatooine', diameter: '10465', rotation_period: '23', terrain: 'desert', gravity: '1 standard', orbital_period: '304', population: '200000',
            },
          },
          modalOpen: false,
          request: {
            isFetching: false,
            query: 'http://it2810-06.idi.ntnu.no/api/api/people?search=luke',
            requestedAt: 1542237712722,
            result: [{
              id: 1,
              name: 'Luke Skywalker',
              height: '172',
              mass: '77',
              hair_color: 'blond',
              skin_color: 'fair',
              eye_color: 'blue',
              birth_year: '19BBY',
              gender: 'male',
              homeworld: 1,
              SpeciesId: null,
              Planet: {
                id: 1, climate: 'arid', surface_water: '1', name: 'Tatooine', diameter: '10465', rotation_period: '23', terrain: 'desert', gravity: '1 standard', orbital_period: '304', population: '200000',
              },
            }],
            searchTerm: 'luke',
          },
          timeout: 34,
          filter: [],
        }, { type: 'OPEN_MODAL' });
        expect(state).toEqual({
          currentPerson: {
            id: 1,
            name: 'Luke Skywalker',
            height: '172',
            mass: '77',
            hair_color: 'blond',
            skin_color: 'fair',
            eye_color: 'blue',
            birth_year: '19BBY',
            gender: 'male',
            homeworld: 1,
            SpeciesId: null,
            Planet: {
              id: 1, climate: 'arid', surface_water: '1', name: 'Tatooine', diameter: '10465', rotation_period: '23', terrain: 'desert', gravity: '1 standard', orbital_period: '304', population: '200000',
            },
          },
          modalOpen: true,
          request: {
            isFetching: false,
            query: 'http://it2810-06.idi.ntnu.no/api/api/people?search=luke',
            requestedAt: 1542237712722,
            result: [{
              id: 1,
              name: 'Luke Skywalker',
              height: '172',
              mass: '77',
              hair_color: 'blond',
              skin_color: 'fair',
              eye_color: 'blue',
              birth_year: '19BBY',
              gender: 'male',
              homeworld: 1,
              SpeciesId: null,
              Planet: {
                id: 1, climate: 'arid', surface_water: '1', name: 'Tatooine', diameter: '10465', rotation_period: '23', terrain: 'desert', gravity: '1 standard', orbital_period: '304', population: '200000',
              },
            }],
            searchTerm: 'luke',
          },
          timeout: 34,
          filter: [],
        });
      });
    });
  });
});
