image: cypress/base:10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install

stages:
  - build
  - fresh_build
  - test

build-job:
  stage: build
  script:
    - npm run build
    - npm run e2e:verify

unittest-job:
  stage: test
  script:
    - npm test
  when: always

integrationtest-job:
  stage: test
  script:
  # start the server in the background
    - npm start --silent &
  # run Cypress test in load balancing mode, pass id to tie jobs together
    - npm run e2e
  when: always
