stages:
  - build
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

install:
  image: cypress/base:10
  stage: build

  script:
    - npm ci
    - $(npm bin)/print-env CI
    - npm run cy:verify

stages:
  - build
  - fresh_build
  - test

build-job:
  stage: build
  script:
    - npm ci
    - $(npm bin)/print-env CI
    - npm run cy:verify

unittest-job:
  stage: test
  script:
    - npm test
  when: always

integrationtest-job:
  stage: test
  script:
  # start the server in the background
    - npm start --silent &
  # run Cypress test in load balancing mode, pass id to tie jobs together
    - npm run e2e
  when: always
